import { PropsWithChildren } from 'react'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { NextIntlClientProvider } from 'next-intl'

import { getTranslations } from '@/i18n'
import RootProvider from '@/providers/RootProvider'
import ThemeRegistry from '@/providers/ThemeRegistry'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  }
}

export default async function RootLayout({ children }: PropsWithChildren) {
  const session = await getServerSession()
  const { messages, locale, theme } = await getTranslations()

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <RootProvider savedTheme={theme} session={session}>
            <ThemeRegistry>{children}</ThemeRegistry>
          </RootProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
